### ISSUE TITLE
NoSuchBeanDefinitionException for AnnotationConfigApplicationContext

### ISSUE THREAD

**Issue by justiniantaylor** [spring-guides/gs-messaging-rabbitmq#10]
I was wondering if you could please help me, I took the exact code from the complete folder and when I try and run it I get the following error:

Caused by:

```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.context.annotation.AnnotationConfigApplicationContext] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
```

It seems to be swearing about

```
    @Autowired
    AnnotationConfigApplicationContext context;
```

I know my rabbit server is running as i have checked with rabbitmqctl status and its all ok. And then I found the RabbitAutoConfigurationTests which all run and pass.

Any idea what I could be doing wrong?

**Comment by dsyer** [comment]
Works for me. What exactly are your steps to repeat?

**Comment by justiniantaylor** [comment]
Hi Dave

Thanks for taking the time to try help.

Well I took the project in the complete folder put it into a project in sts and right click on project and select run as spring boot application, am I doing something really stupid hehe?

Thanks kindly
Justin

**Comment by dsyer** [comment]
Still works for me. I'm importing as a Maven project. It also works fine if I build the jar and run it on the command line.

**Comment by justiniantaylor** [comment]
it wont let me build it gives me that exception on compile so I am pretty clueless here. Any idea what might cause AnnotationConfigApplicationContext to not be autowired?

**Comment by justiniantaylor** [comment]
Ah I am being an idiot Dave sorry, I had my boot project being packaged as was, changed it to jar and removed my servlet initializer and it works now.

Thanks for your time! Awesome work you do by the way, thanks very much!
