### ISSUE TITLE
Dead link.

### ISSUE THREAD

**Issue by milkwarlok** [spring-guides/gs-messaging-rabbitmq#20]
There is a dead link in README.adoc:
"There's http://docs.spring.io/spring-amqp/reference/html/_introduction.html#quick-tour[more you can do with Spring and RabbitMQ] than what is covered here, but this should provide a good start."

_Should be replaced with:_
"There's https://docs.spring.io/spring-amqp/reference/#quick-tour[more you can do with Spring and RabbitMQ] than what is covered here, but this should provide a good start."

Regards

**Comment by dsyer** [comment]
I think this issue is obsoleted by recent changes.
