### ISSUE TITLE
The POM for org.springframework.boot:spring-boot-starter-amqp:jar:2.1.4.RELEASE is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

### ISSUE THREAD

**Issue by hannesgeodan** [spring-guides/gs-messaging-rabbitmq#24]
When I compile the checkout (complete folder), i get this warning:

**The POM for org.springframework.boot:spring-boot-starter-amqp:jar:2.1.4.RELEASE is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details**

**Comment by dsyer** [comment]
Works for me. Maybe you have an invalid pom or jar in your local `~/.m2` cache?
