### ISSUE TITLE
cannot access hello - zip END header not found

### ISSUE THREAD

**Issue by hannesgeodan** [spring-guides/gs-messaging-rabbitmq#25]
With starter 2.1.4.RELEASE I get the following error with mvn compile.

**[ERROR] /tmp/rabbit/gs-messaging-rabbitmq/complete/src/main/java/hello/Runner.java:[1,1] cannot access hello
[ERROR]   zip END header not found**

And a lot more ERRORs like this.

**Comment by dsyer** [comment]
There is some missing context here. What did you do (step by step) and what did you see (complete terminal logs)?
