### ISSUE TITLE
Docker compose file for RabbitMQ throws an error

### ISSUE THREAD

**Issue by Manish-Giri** [spring-guides/gs-messaging-rabbitmq#40]
Based on the instructions here - https://github.com/spring-guides/gs-messaging-rabbitmq?tab=readme-ov-file#what-you-need

The docker compose file for installing rabbitmq looks like this

```
rabbitmq:
  image: rabbitmq:management
  ports:
    - "5672:5672"
    - "15672:15672"
```

This is either incomplete or incorrect, because `docker-compose up` command fails with this file.

```
D:\Downloads\messaging-rabbitmq
docker-compose up
validating D:\Downloads\messaging-rabbitmq\docker-compose.yml: (root) Additional property rabbitmq is not allowed
```

Version information
```
D:\Downloads\messaging-rabbitmq
docker compose version
Docker Compose version v2.24.3-desktop.1


D:\Downloads\messaging-rabbitmq
docker version
Client:
 Cloud integration: v1.0.35+desktop.10
 Version:           25.0.2
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629
 Built:             Thu Feb  1 00:24:09 2024
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.27.1 (136059)
 Engine:
  Version:          25.0.2
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       fce6e0c
  Built:            Thu Feb  1 00:23:17 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0

```

**Comment by robertmcnees** [comment]
Hi @Manish-Giri ,

Thanks for the issue.  It looks like the documentation doesn't have the `services:` top-level element.

Can you see if using the [docker-compose.yml](https://github.com/spring-guides/gs-messaging-rabbitmq/blob/main/complete/docker-compose.yml) specified in the project works?

We should have the [documentation](https://github.com/spring-guides/gs-messaging-rabbitmq/blob/ff2476dfc513539f5d2d2fb5604514cf1af7c5f7/README.adoc?plain=1#L75) match the [code](https://github.com/spring-guides/gs-messaging-rabbitmq/blob/ff2476dfc513539f5d2d2fb5604514cf1af7c5f7/complete/docker-compose.yml#L3). Would like to submit a PR?

**Comment by robertmcnees** [comment]
Instead of a copy/paste, we can link to the `docker-compose.yml` file similar to [other places in the documentation](https://github.com/robertmcnees/gs-messaging-rabbitmq/blob/ff2476dfc513539f5d2d2fb5604514cf1af7c5f7/README.adoc?plain=1#L183). That way if the documentation won't get out of sync for potential future changes.

**Comment by Manish-Giri** [comment]
Sounds good! Thank you for the instructions, I'll create a PR for this change.

**Comment by Manish-Giri** [comment]
@robertmcnees Here's the PR - https://github.com/spring-guides/gs-messaging-rabbitmq/pull/42

One item I wanted to highlight - the include directive doesn't seem to correctly render code in place of the "included" link, I just see a link instead of the intended code. Here are a couple of screenshots from the readme doc that attempts to use the include -

![image](https://github.com/spring-guides/gs-messaging-rabbitmq/assets/11348778/7e1ae0ca-099f-47c9-a1f0-a3052c97f039)

![image](https://github.com/spring-guides/gs-messaging-rabbitmq/assets/11348778/fa605ed1-71a4-43e3-832d-316a28c79227)

Not sure if this is already a known issue or it is and caused due to "[safe modes](https://docs.asciidoctor.org/asciidoctor/latest/safe-modes/)".

**Comment by robertmcnees** [comment]
@Manish-Giri 

Thanks for the PR!  I merged it and you can see the [results now live](https://spring.io/guides/gs/messaging-rabbitmq).

Regarding the rendering issue, it might be an issue with your local environment. I'm using IntelliJ and the links render fine in the preview panel. I am not an AsciiDoc expert so I'm afraid I can't be more help.

Thank you for your contribution!
